name: continuous delivery

on: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js 12.14.0
        uses: actions/setup-node@master
        with:
          node-version: 12.14.0
      - name: Install dependencies
        run: yarn
        env:
          CI: true
      - name: build
        run: yarn build
        env:
          CI: true
      - name: publish
        run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
