name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js 12.14.0
        uses: actions/setup-node@master
        with:
          node-version: 12.14.0
      - name: Install dependencies
        run: yarn
        env:
          CI: true
      - name: lint
        run: yarn lint
        env:
          CI: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js 12.14.0
        uses: actions/setup-node@master
        with:
          node-version: 12.14.0
      - name: Install dependencies
        run: yarn
        env:
          CI: true
      - name: Test
        run: yarn test
        env:
          CI: true
